# Generated by Django 5.2.17 on 2026-09-29 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('search', 'Recherche'), ('address', 'Adresse saisie'), ('visit', 'Page visitée')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.CharField(max_length=120)),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=512)),
                ('query', models.CharField(blank=True, max_length=2048)),
                ('peer_ip', models.GenericIPAddressField(null=True)),
                ('interfaces', models.JSONField(default=list)),
                ('consent_version', models.PositiveSmallIntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.device')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['device', 'received_at'], name='monitor_eve_device__5ee413_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'event_id'), name='unique_device_event')],
            },
        ),
    ]
